// Słownik mięśni sylwetki: nazwa, funkcja, kolor, ćwiczenia na dany mięsień
// i warstwa anatomiczna. Osobny moduł, bo poza mapą korzysta z niego edytor
// planów (chipy mięśni) — a klucze muszą zgadzać się z MUSCLE_IDS
// w shared/planSchema.mjs.
export const MUSCLES = {
  deltoid_front:{name:"Mięsień naramienny",latin:"Deltoideus",function:"Odwodzenie i zginanie ramienia, rotacja wewnętrzna i zewnętrzna; stabilizacja stawu ramiennego podczas dźwigania",location:"Ramię – okrywa staw ramienny z trzech stron",side:"front",color:"#FF6D3A",exercises:[{name:"Wyciskanie nad głowę na maszynie",sets:"4 × 10–12",tip:"Ustaw uchwyty na wysokości barków. Wypychaj płynnie bez blokowania łokci.",icon:"⚙️"},{name:"Odwodzenie ramion na maszynie",sets:"3 × 12–15",tip:"Unoś łokcie do linii barków, kontroluj opuszczanie 2–3 s.",icon:"⚙️"},{name:"Wyciąg linkowy – unoszenie w przód",sets:"3 × 12",tip:"Unoś wyprostowane ramię do wysokości oczu, bez bujania tułowiem.",icon:"⚙️"},{name:"Wyciskanie żołnierskie ze sztangą",sets:"4 × 6–8",tip:"Wypychaj pionowo, głowa cofa się by przepuścić gryf, pośladki napięte.",icon:"🏋️"},{name:"Odwodzenie ramion z hantlami",sets:"3 × 12–15",tip:"Prowadź ruch łokciami. Nie unoś powyżej linii barków.",icon:"🏋️"},{name:"Wyciskanie Arnolda",sets:"3 × 10",tip:"Obracaj nadgarstki o 180° podczas wyciskania.",icon:"🔄"}]},
  pectoralis:{name:"Mięsień piersiowy większy",latin:"Pectoralis major",function:"Przyciąganie i rotacja wewnętrzna ramienia, zginanie ramienia w stawie barkowym",location:"Klatka piersiowa – od mostka i obojczyka do kości ramiennej",side:"front",color:"#F44336",exercises:[{name:"Wyciskanie na maszynie",sets:"4 × 10–12",tip:"Wypychaj ściągając łopatki, zatrzymaj tuż przed pełnym wyprostem.",icon:"⚙️"},{name:"Rozpiętki na maszynie (Pec Deck)",sets:"3 × 12–15",tip:"Zbliżaj ramiona po łuku, ściskając klatkę 1 s.",icon:"⚙️"},{name:"Zbliżanie ramion na wyciągu",sets:"3 × 12",tip:"Prowadź dłonie po łuku w dół i do środka, krzyżując nisko.",icon:"⚙️"},{name:"Wyciskanie sztangi na ławce",sets:"4 × 6–8",tip:"Łopatki ściągnięte, gryf opada do linii sutków, łokcie ~75°.",icon:"🏋️"},{name:"Rozpiętki z hantlami",sets:"3 × 12",tip:"Lekko zgięte łokcie, nie schodź poniżej linii ławki.",icon:"🏋️"},{name:"Pompki diamentowe / klasyczne",sets:"3 × do załamania",tip:"Ciało w linii prostej, brzuch napięty.",icon:"💎"}]},
  biceps:{name:"Mięsień dwugłowy ramienia",latin:"Biceps brachii",function:"Zginanie łokcia, supinacja przedramienia, pomocniczo zginanie ramienia",location:"Przednia część ramienia – od łopatki do kości promieniowej",side:"front",color:"#42A5F5",exercises:[{name:"Uginanie ramion na maszynie",sets:"4 × 10–12",tip:"Ramię oparte, pełen zakres, kontrolowany powrót.",icon:"⚙️"},{name:"Uginanie na wyciągu z drążkiem",sets:"3 × 12",tip:"Łokcie przyklejone do tułowia przez cały ruch.",icon:"⚙️"},{name:"Uginanie na modlitewniku",sets:"3 × 10",tip:"Zatrzymaj przed pełnym wyprostem, by chronić ścięgno.",icon:"⚙️"},{name:"Uginanie ze sztangą",sets:"4 × 8–10",tip:"Nie bujaj tułowiem, powolne opuszczanie 2–3 s.",icon:"💪"},{name:"Uginanie młotkowe",sets:"3 × 12",tip:"Chwyt neutralny, buduje grubość ramienia.",icon:"🔨"},{name:"Uginanie z supinacją",sets:"3 × 10",tip:"Obracaj nadgarstek na zewnątrz podczas unoszenia.",icon:"🔄"}]},
  rectus_abdominis:{name:"Mięsień prosty brzucha",latin:"Rectus abdominis",function:"Zginanie tułowia, stabilizacja miednicy i kręgosłupa, wspomaganie wydechu",location:"Przednia ściana brzucha – od mostka do spojenia łonowego",side:"front",color:"#66BB6A",exercises:[{name:"Spięcia brzucha na maszynie",sets:"4 × 15",tip:"Ruch zwijaniem tułowia, nie ciągnięciem rękami.",icon:"⚙️"},{name:"Spięcia na wyciągu górnym",sets:"3 × 15",tip:"Zwijaj kręgosłup 'kręg po kręgu', biodra nieruchome.",icon:"⚙️"},{name:"Unoszenie nóg (Captain's Chair)",sets:"3 × 12",tip:"Unoś kolana zwijając miednicę.",icon:"⚙️"},{name:"Klasyczne spięcia (Crunch)",sets:"3 × 20",tip:"Unoś tylko łopatki, dół pleców przy macie.",icon:"🔃"},{name:"Unoszenie nóg w zwisie",sets:"3 × 12",tip:"Kontroluj opuszczanie, zwijaj miednicę ku żebrom.",icon:"⬆️"},{name:"Deska (Plank)",sets:"3 × 45–60 s",tip:"Ciało w linii prostej, napnij brzuch i pośladki.",icon:"📏"}]},
  obliques:{name:"Mięśnie skośne brzucha",latin:"Obliquus externus / internus",function:"Rotacja i boczne zginanie tułowia, stabilizacja core",location:"Boczne ściany brzucha, po bokach mięśnia prostego",side:"front",color:"#FF6E40",exercises:[{name:"Rotacja tułowia na maszynie",sets:"4 × 15",tip:"Miednica unieruchomiona, rotuj wyłącznie tułowiem.",icon:"⚙️"},{name:"Drwal na wyciągu (Woodchopper)",sets:"3 × 12",tip:"Ruch diagonalny od barku do przeciwnego biodra.",icon:"⚙️"},{name:"Boczne spięcia na wyciągu",sets:"3 × 15",tip:"Zginaj się bocznie w talii, pełne rozciągnięcie u góry.",icon:"⚙️"},{name:"Russian Twist z obciążeniem",sets:"3 × 20",tip:"Odchyl tułów ~45°, rotuj tułowiem nie rękami.",icon:"🔄"},{name:"Boczna deska (Side Plank)",sets:"3 × 30–45 s",tip:"Ciało w jednej linii, biodro wysoko.",icon:"📐"},{name:"Skłony boczne z hantlem",sets:"3 × 15",tip:"Zginaj bocznie tylko w talii, nie rotuj.",icon:"🏋️"}]},
  serratus:{name:"Mięsień zębaty przedni",latin:"Serratus anterior",function:"Protrakcja i rotacja łopatki w górę, dociskanie łopatki do klatki",location:"Boczna ściana klatki – od żeber do brzegu łopatki",side:"front",color:"#26C6DA",exercises:[{name:"Wypychanie z protrakcją na wyciągu",sets:"4 × 15",tip:"Na końcu ruchu 'wypchnij' łopatkę do przodu.",icon:"⚙️"},{name:"Pullover na wyciągu",sets:"3 × 12",tip:"Ciągnij łukiem do bioder, czując pracę pod pachą.",icon:"⚙️"},{name:"Wyciskanie w Smith z protrakcją",sets:"3 × 12",tip:"W górnej fazie 'dopchnij' barki do sufitu.",icon:"⚙️"},{name:"Pompki z protrakcją (Push-up Plus)",sets:"3 × 15",tip:"Na szczycie wypchnij górną część pleców w górę.",icon:"🤸"},{name:"Pullover z hantlem",sets:"3 × 12",tip:"Opuszczaj za głowę czując rozciąganie żeber.",icon:"🔁"},{name:"Wall Slides",sets:"3 × 12",tip:"Przesuwaj przedramiona w górę wysuwając łopatki.",icon:"🧱"}]},
  forearm_front:{name:"Przedramię – zginacze",latin:"Flexores antebrachii",function:"Zginanie nadgarstka i palców, siła chwytu, pronacja",location:"Przednia strona przedramienia",side:"front",color:"#29B6F6",exercises:[{name:"Uginanie nadgarstków na wyciągu",sets:"4 × 15",tip:"Przedramiona oparte, tylko dłonie ruchome.",icon:"⚙️"},{name:"Ściskanie uchwytu (Grip Machine)",sets:"3 × 15",tip:"Powolne ściskanie i kontrolowany powrót.",icon:"⚙️"},{name:"Farmer's Walk",sets:"3 × 40 m",tip:"Barki w dół, tułów wyprostowany.",icon:"🏋️"},{name:"Uginanie nadgarstków ze sztangą",sets:"3 × 15–20",tip:"Rozwiń gryf do końców palców, potem zwiń.",icon:"🤲"},{name:"Wieszanie na drążku (Dead Hang)",sets:"3 × do załamania",tip:"Zwis na wyprostowanych ramionach.",icon:"🏗️"},{name:"Wrist Roller",sets:"3 × 2 przejścia",tip:"Zwijaj linę z obciążeniem obracając nadgarstkami.",icon:"🎯"}]},
  quadriceps:{name:"Mięsień czworogłowy uda",latin:"Quadriceps femoris",function:"Prostowanie kolana, zginanie biodra, stabilizacja rzepki",location:"Przednia część uda – cztery głowy",side:"front",color:"#AB47BC",exercises:[{name:"Prostowanie nóg (Leg Extension)",sets:"4 × 12–15",tip:"Pełen wyprost z 1 s napięcia u góry.",icon:"⚙️"},{name:"Wypychanie na suwnicy (Leg Press)",sets:"4 × 10–12",tip:"Kolana podążają za palcami, nie blokuj u góry.",icon:"⚙️"},{name:"Przysiad Hack",sets:"3 × 10",tip:"Plecy płasko, napęd przez pięty.",icon:"⚙️"},{name:"Przysiad ze sztangą",sets:"4 × 6–8",tip:"Kolana nad stopami, pięty na podłodze.",icon:"🏋️"},{name:"Wykroki chodzone",sets:"3 × 12",tip:"Długi krok, tułów pionowo, napęd z pięty.",icon:"🦵"},{name:"Przysiad bułgarski",sets:"3 × 10",tip:"Tylna stopa na podwyższeniu, schodź pionowo.",icon:"🔥"}]},
  adductors:{name:"Mięśnie przywodziciele uda",latin:"Adductores femoris",function:"Przywodzenie uda, rotacja i stabilizacja biodra",location:"Przyśrodkowa część uda",side:"front",color:"#EC407A",exercises:[{name:"Przywodzenie ud na maszynie",sets:"4 × 15",tip:"Zbliżaj uda, zatrzymaj w zwarciu 1 s.",icon:"⚙️"},{name:"Przywodzenie na wyciągu",sets:"3 × 15",tip:"Przeciągaj nogę przez linię środkową ciała.",icon:"⚙️"},{name:"Suwnica – wąskie stopy",sets:"3 × 12",tip:"Stopy blisko siebie, palce lekko na zewnątrz.",icon:"⚙️"},{name:"Przysiad sumo",sets:"3 × 10",tip:"Szeroki rozkrok, palce na zewnątrz 45°.",icon:"🏋️"},{name:"Wykrok boczny (Cossack)",sets:"3 × 10",tip:"Duży krok w bok, biodra cofnięte.",icon:"↔️"},{name:"Ściskanie piłki (Copenhagen)",sets:"3 × 30 s",tip:"Ściskaj piłkę udami statycznie lub dynamicznie.",icon:"⚽"}]},
  tibialis:{name:"Mięsień piszczelowy przedni",latin:"Tibialis anterior",function:"Zginanie grzbietowe stopy, inwersja, stabilizacja chodu",location:"Przednio-boczna część goleni",side:"front",color:"#26A69A",exercises:[{name:"Zginanie grzbietowe na maszynie",sets:"4 × 15–20",tip:"Unoś palce ku goleni, pauza u góry.",icon:"⚙️"},{name:"Zginanie stopy z linką",sets:"3 × 15",tip:"Przyciągaj palce do siebie przeciw oporowi.",icon:"⚙️"},{name:"Wypychanie palcami na suwnicy",sets:"3 × 15",tip:"Kontrolowane zginanie grzbietowe stopy.",icon:"⚙️"},{name:"Chód na piętach",sets:"3 × 30 m",tip:"Unieś palce maksymalnie, idź na piętach.",icon:"🚶"},{name:"Unoszenie palców z taśmą",sets:"3 × 20",tip:"Przyciągaj palce ku sobie przeciw taśmie.",icon:"🎗️"},{name:"Unoszenie palców pod ścianą",sets:"3 × 20",tip:"Pięty przy ścianie, unoś przód stóp wysoko.",icon:"👣"}]},
  sartorius:{name:"Mięsień krawiecki",latin:"Sartorius",function:"Zginanie, odwodzenie i rotacja zewnętrzna uda; zginanie goleni",location:"Najdłuższy mięsień ciała – ukośnie przez przód uda",side:"front",color:"#D4E157",exercises:[{name:"Zginanie biodra na wyciągu",sets:"4 × 12",tip:"Unoś kolano z lekką rotacją zewnętrzną.",icon:"⚙️"},{name:"Odwodzenie z rotacją na maszynie",sets:"3 × 15",tip:"Akcent na rotację zewnętrzną biodra.",icon:"⚙️"},{name:"Zginanie biodra w maszynie",sets:"3 × 12",tip:"Kontroluj tempo, unikaj zamachów.",icon:"⚙️"},{name:"Unoszenie kolana z rotacją",sets:"3 × 12",tip:"Obracaj kolano na zewnątrz jak do siadu skrzyżnego.",icon:"🦵"},{name:"Wykrok krzyżowy (Curtsy)",sets:"3 × 10",tip:"Krok po skosie za drugą nogę.",icon:"🔄"},{name:"Siad skrzyżny (Butterfly)",sets:"3 × 30 s",tip:"Stopniowo pogłębiaj rotację bioder.",icon:"🧘"}]},
  trapezius:{name:"Mięsień czworoboczny",latin:"Trapezius",function:"Unoszenie, cofanie i rotacja łopatki; prostowanie głowy i szyi",location:"Górna część pleców i kark",side:"back",color:"#FF7043",exercises:[{name:"Wznosy barków na maszynie",sets:"4 × 12–15",tip:"Unoś barki prosto w górę, pauza 1 s. Nie rotuj.",icon:"⚙️"},{name:"Face Pull na wyciągu",sets:"3 × 15",tip:"Lina na wysokości oczu, łokcie wysoko.",icon:"⚙️"},{name:"Wiosłowanie z akcentem na łopatki",sets:"3 × 12",tip:"Mocno ściągnij łopatki do siebie, pauza.",icon:"⚙️"},{name:"Wznosy barków ze sztangą",sets:"4 × 12",tip:"Unoś barki pionowo, bez bujania.",icon:"🏋️"},{name:"Wznosy barków z hantlami",sets:"3 × 15",tip:"Neutralny chwyt, pełen zakres.",icon:"🏋️"},{name:"Prone Y-Raise",sets:"3 × 15",tip:"Unoś ramiona tworząc literę Y – dolny czworoboczny.",icon:"✌️"}]},
  deltoid_back:{name:"Naramienny – część tylna",latin:"Deltoideus (posterior)",function:"Prostowanie i rotacja zewnętrzna ramienia, odwodzenie poziome",location:"Tylna część barku",side:"back",color:"#FF8A65",exercises:[{name:"Odwrotne rozpiętki na maszynie",sets:"4 × 12–15",tip:"Ramiona odwodzone w tył po łuku, ściśnij łopatki.",icon:"⚙️"},{name:"Odwodzenie w tył na wyciągu",sets:"3 × 15",tip:"Ciągnij ramiona na zewnątrz i w tył.",icon:"⚙️"},{name:"Face Pull",sets:"3 × 15",tip:"Łokcie wysoko i szeroko.",icon:"⚙️"},{name:"Odwrotne rozpiętki z hantlami",sets:"4 × 15",tip:"Tułów pochylony ~45°, prowadź łokciami.",icon:"🏋️"},{name:"Odwodzenie hantla w opadzie",sets:"3 × 12",tip:"Podpór ręką o ławkę, izolacja tyłu barku.",icon:"🔄"},{name:"Odwodzenie poziome leżąc",sets:"3 × 15",tip:"Leżąc przodem, unoś ramiona w bok.",icon:"🛏️"}]},
  infraspinatus:{name:"Mięsień podgrzebieniowy",latin:"Infraspinatus",function:"Rotacja zewnętrzna ramienia, stabilizacja (stożek rotatorów)",location:"Tylna powierzchnia łopatki",side:"back",color:"#80DEEA",exercises:[{name:"Rotacja zewnętrzna na wyciągu",sets:"4 × 15",tip:"Łokieć przy tułowiu, obracaj przedramię na zewnątrz.",icon:"⚙️"},{name:"Rotacja na maszynie do rotatorów",sets:"3 × 15",tip:"Powolny ruch w pełnym zakresie.",icon:"⚙️"},{name:"Face Pull z rotacją",sets:"3 × 12",tip:"Na końcu obróć dłonie ku sufitowi.",icon:"⚙️"},{name:"Rotacja leżąc na boku",sets:"3 × 15",tip:"Bardzo lekki ciężar (1–3 kg), pełny zakres.",icon:"↩️"},{name:"Rotacja z taśmą",sets:"3 × 15",tip:"Ramię przy ciele, powolne obracanie.",icon:"🎗️"},{name:"Prone W",sets:"3 × 12",tip:"Ramiona tworzą literę W, kciuki ku górze.",icon:"🅆"}]},
  latissimus:{name:"Mięsień najszerszy grzbietu",latin:"Latissimus dorsi",function:"Prostowanie, przywodzenie i rotacja wewnętrzna ramienia; podciąganie",location:"Dolna i środkowa część pleców",side:"back",color:"#FF4081",exercises:[{name:"Ściąganie drążka (Lat Pulldown)",sets:"4 × 10–12",tip:"Ściągaj do górnej klatki, łopatki najpierw.",icon:"⚙️"},{name:"Wiosłowanie na maszynie",sets:"4 × 10–12",tip:"Ściągaj do brzucha, ściągając łopatki.",icon:"⚙️"},{name:"Ściąganie prostymi ramionami",sets:"3 × 12",tip:"Izoluje najszerszy bez udziału bicepsa.",icon:"⚙️"},{name:"Podciąganie na drążku",sets:"4 × do załamania",tip:"Inicjuj ściągnięciem łopatek, mostkiem do drążka.",icon:"🏗️"},{name:"Wiosłowanie sztangą w opadzie",sets:"4 × 8",tip:"Tułów ~45°, ściągaj do dolnych żeber.",icon:"⬇️"},{name:"Wiosłowanie hantlem jednorącz",sets:"3 × 10",tip:"Ciągnij hantel do biodra, pełny skurcz łopatki.",icon:"💪"}]},
  erector_spinae:{name:"Mięsień prostownik grzbietu",latin:"Erector spinae",function:"Prostowanie i stabilizacja kręgosłupa, utrzymanie postawy",location:"Wzdłuż całego kręgosłupa",side:"back",color:"#A5D6A7",exercises:[{name:"Prostowanie grzbietu na maszynie",sets:"4 × 12–15",tip:"Nie przeprostowuj lędźwi, zatrzymaj w linii ciała.",icon:"⚙️"},{name:"Martwy ciąg na Smith",sets:"3 × 8–10",tip:"Plecy proste, napęd biodrami.",icon:"⚙️"},{name:"Hiperekstensje (Roman Chair)",sets:"3 × 15",tip:"Prostuj tułów kontrolowanie, bez przeprostu.",icon:"⚙️"},{name:"Martwy ciąg klasyczny",sets:"4 × 5",tip:"Plecy proste, napęd przez pięty i biodra.",icon:"🏋️"},{name:"Good Morning",sets:"3 × 10",tip:"Skłon w biodrach z prostymi plecami.",icon:"🌅"},{name:"Superman",sets:"3 × 15",tip:"Unoś ręce i nogi jednocześnie, pauza 2 s.",icon:"🦸"}]},
  gluteus:{name:"Mięsień pośladkowy wielki",latin:"Gluteus maximus",function:"Prostowanie i rotacja zewnętrzna uda, stabilizacja miednicy",location:"Pośladek – największy mięsień ciała",side:"back",color:"#FFD54F",exercises:[{name:"Wypychanie bioder na maszynie",sets:"4 × 10–12",tip:"Wypychaj do pełnego wyprostu, ściskaj pośladki 1 s.",icon:"⚙️"},{name:"Odpychanie nogi na wyciągu",sets:"3 × 15",tip:"Prostuj biodro, ruch z biodra nie z lędźwi.",icon:"⚙️"},{name:"Suwnica – stopy wysoko",sets:"3 × 12",tip:"Szeroki rozstaw, głębokie schodzenie.",icon:"⚙️"},{name:"Hip Thrust ze sztangą",sets:"4 × 10",tip:"Wypychaj do linii tułów-uda, pełny skurcz.",icon:"🏋️"},{name:"Przysiad bułgarski",sets:"3 × 10",tip:"Tułów lekko pochylony w przód.",icon:"🦵"},{name:"Wchodzenie na podwyższenie",sets:"3 × 12",tip:"Wchodź napędem pięty, prostując biodro.",icon:"📦"}]},
  hamstrings:{name:"Mięśnie kulszowo-goleniowe",latin:"Hamstrings",function:"Zginanie kolana, prostowanie biodra, stabilizacja kolana",location:"Tylna część uda – trzy mięśnie",side:"back",color:"#CE93D8",exercises:[{name:"Uginanie nóg leżąc",sets:"4 × 12",tip:"Uginaj pełnym zakresem, powolny powrót.",icon:"⚙️"},{name:"Uginanie nóg siedząc",sets:"3 × 12–15",tip:"Mocny skurcz w końcowej fazie.",icon:"⚙️"},{name:"Martwy ciąg rumuński na Smith",sets:"3 × 10",tip:"Biodra cofnięte, wracaj napędem bioder.",icon:"⚙️"},{name:"Martwy ciąg rumuński",sets:"4 × 8",tip:"Kolana lekko ugięte, schodź do rozciągnięcia.",icon:"🏋️"},{name:"Nordic Hamstring Curl",sets:"3 × 6–8",tip:"Opuszczaj tułów jak najwolniej hamując.",icon:"🔥"},{name:"Glute-Ham Raise / Bridge",sets:"3 × 12",tip:"Napęd łączy pośladki i tylną taśmę uda.",icon:"🌉"}]},
  gastrocnemius:{name:"Mięsień brzuchaty łydki",latin:"Gastrocnemius",function:"Zginanie podeszwowe stopy, zginanie kolana, napęd",location:"Tylna część goleni – dwie głowy",side:"back",color:"#B39DDB",exercises:[{name:"Wspięcia na palce stojąc",sets:"4 × 15–20",tip:"Głębokie opuszczenie pięt, maksymalne wspięcie.",icon:"⚙️"},{name:"Wypychanie palcami na suwnicy",sets:"3 × 15",tip:"Kolana wyprostowane, pełny zakres kostki.",icon:"⚙️"},{name:"Wspięcia w Smith",sets:"3 × 15",tip:"Skup się na pełnym skurczu łydki.",icon:"⚙️"},{name:"Wspięcia ze sztangą",sets:"3 × 15",tip:"Kolana wyprostowane, akcent na brzuchaty.",icon:"🏋️"},{name:"Wspięcia jednonóż",sets:"3 × 15",tip:"Większe obciążenie i pełen zakres.",icon:"👣"},{name:"Skoki na skakance",sets:"3 × 2 min",tip:"Ląduj miękko na przodostopiu.",icon:"🪢"}]},
  triceps:{name:"Mięsień trójgłowy ramienia",latin:"Triceps brachii",function:"Prostowanie łokcia, prostowanie ramienia, stabilizacja łokcia",location:"Tylna część ramienia – trzy głowy",side:"back",color:"#64B5F6",exercises:[{name:"Prostowanie na wyciągu (Pushdown)",sets:"4 × 12–15",tip:"Łokcie przyklejone do tułowia, pełen wyprost.",icon:"⚙️"},{name:"Prostowanie nad głowę na wyciągu",sets:"3 × 12",tip:"Angażuje głowę długą trójgłowego.",icon:"⚙️"},{name:"Prostowanie w maszynie (Dips)",sets:"3 × 12",tip:"Pełny wyprost z akcentem na skurcz.",icon:"⚙️"},{name:"Wyciskanie wąskim chwytem",sets:"4 × 8",tip:"Łokcie blisko tułowia, napęd trójgłowym.",icon:"🏋️"},{name:"Pompki na poręczach",sets:"3 × do załamania",tip:"Tułów pionowo, łokcie do tyłu.",icon:"🔽"},{name:"Wyprost w opadzie (Kickback)",sets:"3 × 12",tip:"Prostuj przedramię w tył, pauza 1 s.",icon:"🔄"}]},
  forearm_back:{name:"Przedramię – prostowniki",latin:"Extensores antebrachii",function:"Prostowanie nadgarstka i palców, supinacja, stabilizacja",location:"Tylna strona przedramienia",side:"back",color:"#4FC3F7",exercises:[{name:"Prostowanie nadgarstków na wyciągu",sets:"4 × 15",tip:"Prostuj nadgarstki w górę, stałe napięcie.",icon:"⚙️"},{name:"Odwrócone uginanie na wyciągu",sets:"3 × 12",tip:"Chwyt nachwytem, angażuje prostowniki.",icon:"⚙️"},{name:"Prostowanie w maszynie",sets:"3 × 15",tip:"Powolny powrót, akcent na prostowniki.",icon:"⚙️"},{name:"Prostowanie nadgarstków z hantlami",sets:"3 × 15",tip:"Unoś grzbiet dłoni, powolne opuszczanie.",icon:"🤲"},{name:"Odwrócone uginanie ze sztangą",sets:"3 × 12",tip:"Chwyt nachwytem, buduje grubość przedramienia.",icon:"💪"},{name:"Wrist Roller w tył",sets:"3 × 2 przejścia",tip:"Zwijaj grzbietem do góry – trening antagonistów.",icon:"🎯"}]},
  sternocleidomastoid:{name:"Mostkowo-obojczykowo-sutkowy",latin:"Sternocleidomastoideus",function:"Obrót głowy, zginanie szyi, unoszenie mostka przy wdechu",location:"Szyja – od wyrostka sutkowatego do mostka i obojczyka",side:"front",color:"#E040FB",exercises:[{name:"Zginanie szyi na maszynie",sets:"3 × 12–15",tip:"Bardzo lekki ciężar, powolny pełen zakres.",icon:"⚙️"},{name:"Rotacja szyi z linką",sets:"3 × 12",tip:"Minimalny opór, kontrola.",icon:"⚙️"},{name:"Zginanie boczne w uprzęży",sets:"3 × 12",tip:"Unikaj gwałtownych szarpnięć.",icon:"⚙️"},{name:"Zginanie szyi z oporem dłoni",sets:"3 × 15",tip:"Dłoń na czole, opór ręki.",icon:"🤲"},{name:"Unoszenie głowy leżąc",sets:"3 × 12",tip:"Unoś brodę ku klatce, kontrolowany powrót.",icon:"⬆️"},{name:"Rotacja głowy z oporem",sets:"3 × 15",tip:"Dłoń na policzku, obracaj przeciw oporowi.",icon:"🔄"}]},
  scalenes:{name:"Mięśnie pochyłe szyi",latin:"Musculi scaleni",function:"Zginanie boczne szyi, stabilizacja, unoszenie żeber (wdech)",location:"Boczna część szyi – do dwóch górnych żeber",side:"front",color:"#CE93D8",exercises:[{name:"Zginanie boczne w maszynie",sets:"3 × 12",tip:"Minimalne obciążenie, priorytet techniki.",icon:"⚙️"},{name:"Boczne zginanie z linką",sets:"3 × 12",tip:"Powolne pochylanie ku barkowi.",icon:"⚙️"},{name:"Trening oddechowy z oporem",sets:"3 × 2 min",tip:"Aktywuje pochyłe jako mięśnie oddechu.",icon:"⚙️"},{name:"Boczne zginanie z oporem dłoni",sets:"3 × 12",tip:"Ruch powolny, bez kompensacji barkiem.",icon:"🤲"},{name:"Rozciąganie boczne szyi",sets:"3 × 30 s",tip:"Opuść bark, delikatnie pociągnij głowę.",icon:"↔️"},{name:"Oddychanie przeponowe",sets:"3 × 2 min",tip:"Świadome rozluźnienie mięśni szyi.",icon:"🧘"}]},
  platysma:{name:"Mięsień szeroki szyi (Platysma)",latin:"Platysma",function:"Napinanie skóry szyi, opuszczanie żuchwy, mimika",location:"Powierzchowna szyja – od obojczyka do żuchwy",side:"front",color:"#F48FB1",exercises:[{name:"Ćwiczenie oporowe żuchwy",sets:"3 × 12",tip:"Bardzo lekkie obciążenie, kontrola.",icon:"⚙️"},{name:"Elektrostymulacja (EMS)",sets:"2 × 15 min",tip:"Uzupełnienie, nie zastępstwo ćwiczeń.",icon:"⚙️"},{name:"Oporowy uchwyt podbródka",sets:"3 × 12",tip:"Poprawia napięcie powierzchowne szyi.",icon:"⚙️"},{name:"Cofanie żuchwy (Chin Tuck)",sets:"3 × 15",tip:"'Podwójny podbródek', pauza 3 s.",icon:"↩️"},{name:"Opór przy otwieraniu ust",sets:"3 × 12",tip:"Dłoń pod żuchwą, otwieraj przeciw oporowi.",icon:"🤲"},{name:"Grymas platysma",sets:"3 × 15",tip:"Ściągnij kąciki ust w dół, trzymaj 5 s.",icon:"😬"}]},
};

// Warstwa anatomiczna: "deep" leży pod "surface". Przełącznik w interfejsie
// pokazuje jedną naraz, dzięki czemu mięśnie głębokie przestają być zasłonięte.
export const MUSCLE_LAYER = {
  platysma:"surface",
  sternocleidomastoid:"deep",
  scalenes:"deep",
  deltoid_front:"surface",
  pectoralis:"surface",
  serratus:"deep",
  rectus_abdominis:"surface",
  obliques:"surface",
  biceps:"surface",
  forearm_front:"surface",
  quadriceps:"surface",
  sartorius:"surface",
  adductors:"deep",
  tibialis:"surface",
  trapezius:"surface",
  deltoid_back:"surface",
  infraspinatus:"deep",
  latissimus:"surface",
  erector_spinae:"deep",
  triceps:"surface",
  forearm_back:"surface",
  gluteus:"surface",
  hamstrings:"surface",
  gastrocnemius:"surface",
};
